// <auto-generated />
using System;
using KennelProgram.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KennelProgram.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211215102059_one2oneDogAndServices")]
    partial class one2oneDogAndServices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("KennelProgram.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CustomerDog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerDogBreed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerDogSocialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("servicesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("servicesId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("KennelProgram.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Birth")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MothersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SocialNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("KennelProgram.Models.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("ClawCutting")
                        .HasColumnType("bit");

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<bool>("HairCut")
                        .HasColumnType("bit");

                    b.Property<bool>("Washing")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("KennelProgram.Models.Customer", b =>
                {
                    b.HasOne("KennelProgram.Models.Services", "services")
                        .WithMany()
                        .HasForeignKey("servicesId");

                    b.Navigation("services");
                });

            modelBuilder.Entity("KennelProgram.Models.Services", b =>
                {
                    b.HasOne("KennelProgram.Models.Dog", "dog")
                        .WithMany()
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dog");
                });
#pragma warning restore 612, 618
        }
    }
}
